### ISSUE TITLE
Could not add key because queue is full

### ISSUE THREAD

**Issue by ljmendoza01** [redis-developer/riot#104]
i'm replicating data from Elasticache to Redis Enterprise cloud using riot-redis live mode and got this error

Could not add key because queue is full

what does this mean? i still have enough memory and ops on my RE database and see no latency issue too.

**Comment by jruaux** [comment]
This could be because updates on the source database are happening faster than RIOT can write them to the target. This situation is described in the documentation: https://developer.redis.com/riot/riot-redis/index.html#live-replication
What data structures are in use in the source database? Are any collection data structures (list, set, sorted set, ...) updated repeatedly at a high frequency?
